sonar.projectKey=express-typescript-starterkit
sonar.projectVersion=0.0.5
sonar.sources=src
sonar.language=ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8
sonar.exclusions=src/**/*.spec.ts
sonar.test.inclusions=test/**/*.spec.ts
sonar.coverage.exclusions=src/**/*.mock.ts,node_modules/*,coverage/lcov-report/*,setup/*,build/*,.vscode/*,certs/*
