name: Production deployment

on:
  push:
    branches: [feature/deploy-gcp]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile-typescript:
    name: Compiling Typescript application and preparing files required for deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing application dependencies
        run: yarn install
      - name: Compiling Typescript files
        run: yarn build
      - name: Debugging locale files
        run: ls -al
